# Utilise une image officielle de Node.js
FROM node:18

# Définir le dossier de travail dans le conteneur
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le reste des fichiers
COPY . .

# Exposer le port utilisé par Vue CLI
EXPOSE 8080

# Commande pour démarrer l'application
CMD ["npm", "run", "serve"]
