services:
  vue-app:
    build: .
    image: portfolio-lucas
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - /app/node_modules
    command: ["npm", "run", "serve"]
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
